# Golang CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  codespell:
    docker:
    - image: circleci/python

    steps:
    - checkout
    - run: sudo pip install codespell
    - run: codespell --skip=".git,./vendor"

workflows:
  version: 2
  flexlm_exporter:
    jobs:
    - codespell:
        filters:
          tags:
            only: /.*/
